"""Side-aware roll candidates — defensive short-PUT rolls (Task #34, 2026-07-29).

User symptom (real briefing, market down hard): "the ROLL ANALYSIS tables
recommend max-credit roll-UPs on underwater short PUTs — NVDA $200P (spot
$190, $10 ITM): 'E ✅ recommended — $250P +$4,182 credit' → $60 ITM; VRT
$290P (spot $223): '$340P recommended' → $117 ITM. The candidates carried
covered-call language ('raises the cap, preserves more upside')."

Two defects pinned here:
  A. Candidate GENERATION offered roll-up candidates on puts with call-side
     descriptions, and generated NO roll-down candidates at all.
  B. The RANKER picked max net credit — on a short put the max-credit roll
     is the deepest-ITM candidate = maximum risk.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from candidate_ranker import rank_candidates
from roll_target import enumerate_roll_candidates
import advise as advise_mod


# ── Fixtures — NVDA-shaped: SHORT PUT $200, spot $190 ($10 ITM) ────────────

def _nvda_put_position(current_mid=9.0):
    return {
        "symbol": "NVDA",
        "positionType": "SHORT_PUT",
        "optionType": "PUT",
        "strikePrice": 200.0,
        "expirationDate": "2026-08-21",
        "quantity": 1,
        "entryPrice": 6.0,
        "currentMid": current_mid,   # underwater
        "daysToExpiry": 23,
        "ivRank": 55,
        "underlyingPrice": 190.0,
    }


def _nvda_put_chain():
    """Chain with strikes above AND below the current $200 strike, so both a
    roll-up and a roll-down are AVAILABLE — the generator must choose sides."""
    def leg(exp, strike, bid, ask, dte, delta):
        return {"expirationDate": exp, "strikePrice": strike, "optionType": "PUT",
                "bid": bid, "ask": ask, "daysToExpiry": dte, "delta": delta,
                "openInterest": 500}
    return {"candidates": [
        # current expiration (anchors current_exp_idx)
        leg("2026-08-21", 200.0, 13.5, 14.5, 23, -0.62),
        # next expiration — same strike, roll-downs, and roll-ups
        leg("2026-09-18", 200.0, 16.0, 17.0, 51, -0.58),
        leg("2026-09-18", 175.0, 9.0, 9.6, 51, -0.35),
        leg("2026-09-18", 150.0, 5.0, 5.4, 51, -0.20),
        leg("2026-09-18", 225.0, 30.0, 31.0, 51, -0.75),
        leg("2026-09-18", 250.0, 52.0, 53.0, 51, -0.88),
        # filler expirations so idx+3 exists
        leg("2026-10-16", 200.0, 18.0, 19.0, 79, -0.55),
        leg("2026-11-20", 175.0, 11.0, 11.8, 114, -0.33),
        leg("2026-11-20", 200.0, 20.0, 21.0, 114, -0.54),
    ]}


def _params(**overrides):
    p = {"min_dte_for_roll": 21}
    p.update(overrides)
    return p


def _non_hold(cands):
    return [c for c in cands if c.id != "A"]


# ── Defect A: generation ───────────────────────────────────────────────────

def test_put_defensive_roll_never_offers_higher_strike():
    """NVDA-shaped $200P, spot $190 (defensive): no candidate strike > 200
    may be generated by default — max-credit roll-ups ($225P/$250P are on the
    chain) are deeper ITM, not defensive."""
    cands = enumerate_roll_candidates(_nvda_put_position(), _nvda_put_chain(), _params())
    offered = [c.instruction["sell_strike"] for c in _non_hold(cands)]
    assert offered, "expected roll candidates to be generated"
    assert all(s <= 200.0 for s in offered), f"put roll-up offered: {offered}"


def test_put_defensive_roll_generates_roll_down_candidates():
    """Roll-DOWN candidates (strike < 200) must exist, with honest net math:
    BTC cost vs STO credit — a roll-down often costs a small debit and the
    netDollars must say so truthfully."""
    pos = _nvda_put_position(current_mid=9.0)
    cands = enumerate_roll_candidates(pos, _nvda_put_chain(), _params())
    downs = [c for c in _non_hold(cands) if c.instruction["sell_strike"] < 200.0]
    assert downs, "no roll-down candidates generated for a defensive put"
    # honest net: new bid credit − close cost, × 100 × qty
    by_strike = {c.instruction["sell_strike"]: c for c in downs}
    assert 175.0 in by_strike and 150.0 in by_strike
    # $175P Sep 18: bid 9.0 − close 9.0 = 0
    c175 = [c for c in downs
            if c.instruction["sell_strike"] == 175.0
            and c.instruction["sell_expiration"] == "2026-09-18"][0]
    assert c175.net_dollars == pytest.approx((9.0 - 9.0) * 100)
    # $150P Sep 18: bid 5.0 − close 9.0 = −$400 debit, shown truthfully
    c150 = by_strike[150.0]
    assert c150.net_dollars == pytest.approx((5.0 - 9.0) * 100)
    assert c150.net_dollars < 0  # small debit for a $50 strike reduction


def test_put_roll_down_description_says_reduces_risk():
    """Put candidates must carry put language — never the covered-call
    'raises the cap' wording, and roll-downs must state the risk reduction."""
    cands = enumerate_roll_candidates(
        _nvda_put_position(), _nvda_put_chain(),
        _params(include_bullish_roll_up=True))
    for c in _non_hold(cands):
        assert "raises the cap" not in c.notes, (
            f"call-side language on a put candidate {c.id}: {c.notes}")
        assert "preserves more upside" not in c.notes
    downs = [c for c in _non_hold(cands) if c.instruction["sell_strike"] < 200.0]
    for c in downs:
        assert "reduces assignment risk" in c.notes.lower() or "Lower strike" in c.notes
        assert "Lower strike" in c.notes


def test_put_roll_up_only_behind_flag_with_warning():
    """Roll-up on a put is a BULLISH conviction trade: absent by default,
    present only behind include_bullish_roll_up=True and labeled with the
    bullish warning. Even when generated, the ranker must never pick it."""
    # Flag off (default): no strike > 200 anywhere
    cands_off = enumerate_roll_candidates(_nvda_put_position(), _nvda_put_chain(), _params())
    assert all(c.instruction["sell_strike"] <= 200.0 for c in _non_hold(cands_off))

    # Flag on: an up candidate exists, with the warning
    cands_on = enumerate_roll_candidates(
        _nvda_put_position(), _nvda_put_chain(),
        _params(include_bullish_roll_up=True))
    ups = [c for c in _non_hold(cands_on) if c.instruction["sell_strike"] > 200.0]
    assert ups, "flag on → bullish roll-up candidate should be enumerated"
    for c in ups:
        assert "BULLISH" in c.notes
        assert "increases assignment risk" in c.notes

    # Ranker never recommends it even when enumerated
    dicts = [{"id": c.id, "netDollars": c.net_dollars,
              "dteExtension": c.dte_extension, "instruction": c.instruction,
              "current_strike": 200.0} for c in cands_on]
    best, _ = rank_candidates(dicts, spot=190.0, option_type="PUT",
                              max_tenor_days=120)
    assert best is not None
    assert best["instruction"]["sell_strike"] <= 200.0


# ── Defect B: ranking ──────────────────────────────────────────────────────

def test_defensive_put_ranker_prefers_strike_reduction_over_credit():
    """Roll-down at a small debit must beat a same-strike big-credit roll for
    a defensive put — max credit = deepest ITM = maximum risk."""
    cands = [
        {"id": "A", "netDollars": 0, "dteExtension": 0, "instruction": None,
         "current_strike": 200.0},
        # same-strike out, big credit (the old max-credit "winner")
        {"id": "B", "netDollars": 4000.0, "dteExtension": 90,
         "instruction": {"sell_strike": 200.0, "sell_expiration": "2026-10-16"},
         "current_strike": 200.0},
        # roll-down, small debit, $50 strike reduction
        {"id": "C", "netDollars": -400.0, "dteExtension": 51,
         "instruction": {"sell_strike": 150.0, "sell_expiration": "2026-09-18"},
         "current_strike": 200.0},
    ]
    best, scores = rank_candidates(cands, spot=190.0, option_type="PUT",
                                   max_tenor_days=120)
    assert best is not None
    assert best["id"] == "C", (
        f"defensive put ranker must prefer strike reduction over credit; "
        f"got {best['id']}; scores: "
        f"{[(s.candidate_id, s.composite_score) for s in scores]}")


def test_call_side_income_roll_unchanged():
    """Regression guard: covered-call roll-up generation, wording, and
    max-credit-plus-rollup-bonus ranking are preserved."""
    pos = {
        "symbol": "SMH", "positionType": "SHORT_CALL", "optionType": "CALL",
        "strikePrice": 600.0, "expirationDate": "2026-08-21", "quantity": 1,
        "entryPrice": 10.0, "currentMid": 8.0, "daysToExpiry": 23,
        "ivRank": 45, "underlyingPrice": 580.0,
    }
    def leg(exp, strike, bid, ask, dte, delta):
        return {"expirationDate": exp, "strikePrice": strike, "optionType": "CALL",
                "bid": bid, "ask": ask, "daysToExpiry": dte, "delta": delta,
                "openInterest": 400}
    chain = {"candidates": [
        leg("2026-08-21", 600.0, 7.5, 8.5, 23, 0.42),
        leg("2026-08-21", 650.0, 2.0, 2.4, 23, 0.18),   # up_same (strike_up=650)
        leg("2026-09-18", 600.0, 14.0, 15.0, 51, 0.45),  # same_next
        leg("2026-09-18", 650.0, 6.0, 6.6, 51, 0.25),    # up_later
        leg("2026-10-16", 600.0, 18.0, 19.0, 79, 0.46),
        leg("2026-11-20", 600.0, 22.0, 23.0, 114, 0.47),  # same_later
    ]}
    cands = enumerate_roll_candidates(pos, chain, _params())
    by_id = {c.id: c for c in cands}
    # Same candidate menu as before the put-side fix
    assert by_id["B"].instruction["sell_strike"] == 600.0
    assert by_id["B"].notes == "Same strike, extend +28d (~4w) — low delta risk"
    assert by_id["C"].instruction["sell_strike"] == 600.0
    assert "re-caps the name" in by_id["C"].notes
    assert by_id["D"].instruction["sell_strike"] == 650.0
    assert by_id["D"].notes == ("Higher strike (+$50), same expiration — "
                                "raises the cap, preserves more upside")
    assert by_id["E"].instruction["sell_strike"] == 650.0
    assert "raises the cap and adds more time" in by_id["E"].notes
    # Ranking with default option_type="CALL" is byte-compatible (max credit
    # + roll-up bonus, tenor-capped)
    dicts = [{"id": c.id, "netDollars": c.net_dollars,
              "dteExtension": c.dte_extension, "instruction": c.instruction,
              "current_strike": 600.0} for c in cands]
    best, _ = rank_candidates(dicts, spot=580.0, max_tenor_days=120)
    best_default, _ = rank_candidates(dicts, spot=580.0, max_tenor_days=120,
                                      option_type="CALL")
    assert best is not None and best_default is not None
    assert best["id"] == best_default["id"]


def test_recommended_candidate_id_respects_side():
    """advise() end-to-end: the table's ✅ recommended pick on a defensive
    short-put roll must never land on a put roll-up (NVDA $200P → $250P bug)."""
    pos = _nvda_put_position(current_mid=9.0)  # 1.5x underwater, ITM
    result = advise_mod.advise(
        position=pos,
        underlying={"lastPrice": 190.0, "outlook": "NEUTRAL"},
        context={"ivRank": 55, "regime": "NORMAL"},
        chain=_nvda_put_chain(),
    )
    cands = {c["id"]: c for c in result.get("rollCandidates") or []}
    assert cands, "expected roll candidates on an underwater ITM put"
    # No enumerated candidate is a roll-up
    for c in cands.values():
        if c["id"] == "A" or not c.get("instruction"):
            continue
        assert float(c["instruction"]["sell_strike"]) <= 200.0
    rec_id = result.get("recommendedCandidateId")
    assert rec_id is not None
    if rec_id != "A":
        rec = cands[rec_id]
        assert float(rec["instruction"]["sell_strike"]) <= 200.0, (
            f"✅ recommended landed on a put roll-up: {rec}")


# ── Task #37 fix 3: STO-leg viability floor ────────────────────────────────

def _nok_put_position():
    """NOK-shaped: 10× short $11P, spot $9.27 — the 2026-07-30 briefing
    proposed rolling into 10× $1P at bid $0.00 / mid $0.00 ('0.0% yield on
    new collateral', '10 spreads @ $0.00/share')."""
    return {
        "symbol": "NOK", "positionType": "SHORT_PUT", "optionType": "PUT",
        "strikePrice": 11.0, "expirationDate": "2026-09-18", "quantity": 10,
        "entryPrice": 1.45, "currentMid": 2.08, "daysToExpiry": 50,
        "ivRank": 55, "underlyingPrice": 9.27,
    }


def _nok_leg(exp, strike, bid, ask, dte, delta):
    return {"expirationDate": exp, "strikePrice": strike, "optionType": "PUT",
            "bid": bid, "ask": ask, "daysToExpiry": dte, "delta": delta,
            "openInterest": 500}


def test_sto_leg_viability_floor():
    """NOK-shaped: the only strike below the roll-down target is a $1P at
    bid $0.00 — a garbage ticket (rule #19). No roll-down candidate may be
    generated; the $1P must never appear."""
    chain = {"candidates": [
        _nok_leg("2026-09-18", 11.0, 2.00, 2.15, 50, -0.72),
        # next expiration: same strike viable, but only a dead $1P below
        _nok_leg("2026-10-16", 11.0, 2.30, 2.50, 78, -0.70),
        _nok_leg("2026-10-16", 1.0, 0.00, 0.05, 78, -0.01),
        # filler expirations so current_exp_idx + 3 exists
        _nok_leg("2026-11-20", 11.0, 2.60, 2.80, 113, -0.68),
        _nok_leg("2026-12-18", 11.0, 2.85, 3.05, 141, -0.66),
    ]}
    cands = enumerate_roll_candidates(_nok_put_position(), chain, _params())
    strikes = [c.instruction["sell_strike"] for c in _non_hold(cands)]
    assert 1.0 not in strikes, f"dead $1P STO leg offered: {strikes}"
    assert all(s == 11.0 for s in strikes), (
        f"only the viable same-strike rolls should remain: {strikes}")


def test_sto_leg_viability_floor_rejects_subdime_mid():
    """A bid > 0 but mid < $0.10 STO leg is still not viable."""
    chain = {"candidates": [
        _nok_leg("2026-09-18", 11.0, 2.00, 2.15, 50, -0.72),
        _nok_leg("2026-10-16", 11.0, 2.30, 2.50, 78, -0.70),
        _nok_leg("2026-10-16", 6.0, 0.05, 0.08, 78, -0.06),  # mid $0.065
        _nok_leg("2026-11-20", 11.0, 2.60, 2.80, 113, -0.68),
        _nok_leg("2026-12-18", 11.0, 2.85, 3.05, 141, -0.66),
    ]}
    cands = enumerate_roll_candidates(_nok_put_position(), chain, _params())
    strikes = [c.instruction["sell_strike"] for c in _non_hold(cands)]
    assert 6.0 not in strikes


def test_sto_leg_viability_floor_keeps_viable_roll_down():
    """A genuinely viable roll-down (bid > 0, mid ≥ $0.10, |δ| ≥ 0.05,
    strike ≥ 40% of spot) still comes through — the floor is a floor, not a
    roll-down ban."""
    chain = {"candidates": [
        _nok_leg("2026-09-18", 11.0, 2.00, 2.15, 50, -0.72),
        _nok_leg("2026-10-16", 11.0, 2.30, 2.50, 78, -0.70),
        _nok_leg("2026-10-16", 6.0, 0.35, 0.45, 78, -0.14),
        _nok_leg("2026-11-20", 11.0, 2.60, 2.80, 113, -0.68),
        _nok_leg("2026-12-18", 11.0, 2.85, 3.05, 141, -0.66),
    ]}
    cands = enumerate_roll_candidates(_nok_put_position(), chain, _params())
    strikes = [c.instruction["sell_strike"] for c in _non_hold(cands)]
    assert 6.0 in strikes, f"viable roll-down was wrongly filtered: {strikes}"


def test_ranker_belt_rejects_dead_quote_and_sub40pct_strike():
    """candidate_ranker's put-mode belt: candidates that CARRY quote keys
    showing a dead leg (no bid, mid < $0.10), or a strike below 40% of spot,
    are never picked. Candidates WITHOUT quote keys are unaffected
    (fail-open for legacy callers / fixtures)."""
    cands = [
        {"id": "A", "netDollars": 0, "dteExtension": 0, "instruction": None,
         "current_strike": 11.0},
        # dead-quote roll-down — massive "reduction" but bid 0 / mid 0
        {"id": "B", "netDollars": -2085.0, "dteExtension": 28,
         "instruction": {"sell_strike": 5.0, "sell_expiration": "2026-10-16",
                         "sell_bid": 0.0, "sell_mid": 0.0, "sell_ask": 0.05},
         "current_strike": 11.0},
        # sub-40%-of-spot strike (no quote keys — strike floor still applies)
        {"id": "C", "netDollars": -2000.0, "dteExtension": 28,
         "instruction": {"sell_strike": 1.0, "sell_expiration": "2026-10-16"},
         "current_strike": 11.0},
        # legit same-strike out, small credit, no quote keys (fail-open)
        {"id": "D", "netDollars": 220.0, "dteExtension": 28,
         "instruction": {"sell_strike": 11.0, "sell_expiration": "2026-10-16"},
         "current_strike": 11.0},
    ]
    best, _ = rank_candidates(cands, spot=9.27, option_type="PUT",
                              max_tenor_days=120)
    assert best is not None
    assert best["id"] == "D", f"belt failed — picked {best['id']}"
