"""
Live-data policer — enforces no-cached-data policy on every briefing.

Reads the snapshot's data_provenance metadata and verifies each data source was
fetched live within its staleness threshold. Returns a PASS/WARN/BLOCK verdict.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional


# Default staleness thresholds (in minutes). Tuneable via config.
_DEFAULT_THRESHOLDS_MARKET = {
    "positions": 30,
    "broker_positions": 30,
    "quotes": 15,
    "chains": 30,
    "iv_ranks": 1440,
    "earnings_calendar": 1440,
}
_DEFAULT_THRESHOLDS_OVERNIGHT = {
    "positions": 1440,
    "broker_positions": 1440,
    "quotes": 480,
    "chains": 480,
    "iv_ranks": 1440,
    "earnings_calendar": 1440,
}

# Critical sources — staleness here triggers BLOCK
_CRITICAL_SOURCES = {"positions", "broker_positions", "quotes", "chains"}

# Source values that are NEVER allowed (= cached/stale by definition)
_DISALLOWED_SOURCES = {"fixture", "cache", "replay", "stale", "missing"}

# Source values that are explicitly allowed for each data type
_ALLOWED_SOURCES = {
    "positions": {"etrade_live"},
    "broker_positions": {"etrade_live", "manual_override"},
    "quotes": {"yfinance", "etrade_live"},
    "chains": {"etrade_live", "yfinance"},
    "iv_ranks": {"yfinance_252d", "etrade_live"},
    "earnings_calendar": {"yfinance"},
}


@dataclass
class StaleSource:
    source: str
    age_minutes: float
    max_allowed_minutes: float
    actual_source: str
    issue: str
    severity: str  # "critical" or "advisory"


@dataclass
class PolicerResult:
    live: bool
    verdict: str  # PASS | WARN | BLOCK
    stale_sources: list = field(default_factory=list)
    panel_md: str = ""
    blocking_sources: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


def _is_market_hours(now: Optional[datetime] = None) -> bool:
    """Approximate US-ET market hours (9:30am-4:00pm ET, Mon-Fri).
    Uses local time as a proxy — doesn't handle holidays.
    """
    now = now or datetime.now()
    if now.weekday() >= 5:  # Sat/Sun
        return False
    return 9 <= now.hour < 17  # rough — better than nothing


def police_data_freshness(
    snapshot_data: dict,
    now: Optional[datetime] = None,
    market_hours_thresholds: Optional[dict] = None,
    overnight_thresholds: Optional[dict] = None,
) -> PolicerResult:
    """
    Inspect snapshot_data["data_provenance"] and decide if every source is fresh.
    """
    now = now or datetime.now()
    market_open = _is_market_hours(now)
    thresholds = (market_hours_thresholds or _DEFAULT_THRESHOLDS_MARKET) if market_open \
        else (overnight_thresholds or _DEFAULT_THRESHOLDS_OVERNIGHT)

    provenance = (snapshot_data or {}).get("data_provenance") or {}

    # If there's no provenance at all → assume stale (the snapshot wasn't
    # generated by a live-aware pipeline, OR the metadata was stripped).
    if not provenance:
        result = PolicerResult(
            live=False,
            verdict="BLOCK",
            stale_sources=[asdict(StaleSource(
                source="(provenance missing)",
                age_minutes=999999,
                max_allowed_minutes=0,
                actual_source="unknown",
                issue=(
                    "Snapshot has no data_provenance metadata. "
                    "Cannot verify any source is live."
                ),
                severity="critical",
            ))],
            blocking_sources=["provenance"],
        )
        result.panel_md = _build_panel(result)
        return result

    stale: list[StaleSource] = []
    blocking: list[str] = []

    for source_name, max_age in thresholds.items():
        meta = provenance.get(source_name, {}) or {}
        actual_source = meta.get("source", "missing")
        fetched_at_str = meta.get("fetched_at")
        fresh_flag = meta.get("fresh", False)

        # Disallowed source (= explicitly cached/stale)
        if actual_source in _DISALLOWED_SOURCES:
            severity = "critical" if source_name in _CRITICAL_SOURCES else "advisory"
            stale.append(StaleSource(
                source=source_name,
                age_minutes=999999,
                max_allowed_minutes=max_age,
                actual_source=actual_source,
                issue=f"source is '{actual_source}' — cached/non-live data is not allowed",
                severity=severity,
            ))
            if severity == "critical":
                blocking.append(source_name)
            continue

        # Source not in the allow-list
        allowed = _ALLOWED_SOURCES.get(source_name, set())
        if allowed and actual_source not in allowed and actual_source != "missing":
            severity = "critical" if source_name in _CRITICAL_SOURCES else "advisory"
            stale.append(StaleSource(
                source=source_name,
                age_minutes=999999,
                max_allowed_minutes=max_age,
                actual_source=actual_source,
                issue=f"source '{actual_source}' not in allow-list {sorted(allowed)}",
                severity=severity,
            ))
            if severity == "critical":
                blocking.append(source_name)
            continue

        # Missing fetch timestamp
        if not fetched_at_str:
            if source_name in _CRITICAL_SOURCES:
                stale.append(StaleSource(
                    source=source_name,
                    age_minutes=999999,
                    max_allowed_minutes=max_age,
                    actual_source=actual_source,
                    issue="no fetched_at timestamp recorded",
                    severity="critical",
                ))
                blocking.append(source_name)
            continue

        # Compute age
        try:
            fetched_at = datetime.fromisoformat(fetched_at_str.replace("Z", "+00:00"))
            if fetched_at.tzinfo:
                fetched_at = fetched_at.replace(tzinfo=None)
            age_minutes = (now - fetched_at).total_seconds() / 60.0
        except (ValueError, TypeError):
            age_minutes = 999999

        if age_minutes > max_age:
            severity = "critical" if source_name in _CRITICAL_SOURCES else "advisory"
            stale.append(StaleSource(
                source=source_name,
                age_minutes=age_minutes,
                max_allowed_minutes=max_age,
                actual_source=actual_source,
                issue=(
                    f"data is {age_minutes:.0f} min old, exceeds {max_age} min limit "
                    f"({'market hours' if market_open else 'overnight'} window)"
                ),
                severity=severity,
            ))
            if severity == "critical":
                blocking.append(source_name)

    # Verdict
    if blocking:
        verdict = "BLOCK"
        live = False
    elif stale:
        verdict = "WARN"
        live = True  # advisory only — briefing is still based on live data, just slightly stale aux sources
    else:
        verdict = "PASS"
        live = True

    result = PolicerResult(
        live=live,
        verdict=verdict,
        stale_sources=[asdict(s) for s in stale],
        blocking_sources=blocking,
    )
    if stale:
        result.panel_md = _build_panel(result)
    return result


def _build_panel(result: PolicerResult) -> str:
    """Markdown warning panel listing each stale/disallowed source."""
    lines = []
    if result.verdict == "BLOCK":
        lines.append("")
        lines.append("## 🚫 Live-Data Policy Violation — DO NOT TRADE")
        lines.append("")
        lines.append(
            "One or more critical data sources are stale or cached. "
            "The briefing was NOT built from live broker / market data. "
            "Refresh the snapshot from live sources before placing any orders."
        )
        lines.append("")
    else:
        lines.append("")
        lines.append("## ⚠️ Live-Data Policy — Advisory")
        lines.append("")
        lines.append(
            "Some non-critical data sources are stale. Critical inputs (positions, "
            "quotes, chains) are still live."
        )
        lines.append("")

    for s in result.stale_sources:
        if isinstance(s, dict):
            sym = s.get("source")
            actual = s.get("actual_source")
            issue = s.get("issue")
            severity = s.get("severity")
        else:
            sym, actual, issue, severity = s.source, s.actual_source, s.issue, s.severity
        emoji = "🔴" if severity == "critical" else "🟡"
        lines.append(f"- {emoji} **{sym}** (source `{actual}`): {issue}")
    lines.append("")
    return "\n".join(lines)
